apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend1-config
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
        <title>Chat Application</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 20px;
                background-color: #fff5f5;
            }
            h1 {
                color: #f05252;
                margin-bottom: 20px;
            }
            .chat-container {
                display: flex;
                gap: 10px;
                margin-bottom: 20px;
            }
            .message-input {
                flex-grow: 1;
                padding: 10px;
                border: 1px solid #f05252;
                border-radius: 4px;
                outline: none;
            }
            .send-button {
                padding: 10px 20px;
                background-color: #f05252;
                color: white;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }
            .send-button:hover {
                background-color: #e02424;
            }
            .chat-box {
                border: 1px solid #f05252;
                border-radius: 4px;
                min-height: 500px;
                padding: 20px;
                background-color: white;
                overflow-y: auto;
            }
            .message {
                margin-bottom: 10px;
                padding: 8px;
                border-radius: 4px;
                background-color: #ffefef;
            }
            .error-message {
                background-color: #ffdede;
                color: #f05252;
                padding: 10px;
                border-radius: 4px;
                margin-bottom: 20px;
            }
        </style>
    </head>
    <body>
        <h1>Home Chat</h1>
        
        <div class="chat-container">
            <input type="text" id="message-input" class="message-input" placeholder="Type your message here..."/>
            <button onclick="sendMessage()" class="send-button">Send</button>
        </div>

        <div id="error-container"></div>
        <div id="chat-box" class="chat-box"></div>
        
        <a href="/room" style="color: #f05252; text-decoration: none;">Go to Room Chat</a>

        <script>
            async function fetchMessages() {
                try {
                    const response = await fetch('/api/messages');
                    
                    if (!response.ok) {
                        throw new Error(`HTTP error! status: ${response.status}`);
                    }
                    
                    const messages = await response.json();  // Direct array from backend
                    console.log('Received messages:', messages);
                    
                    if (Array.isArray(messages)) {
                        displayMessages(messages);
                    } else {
                        console.error('Invalid response format');
                        displayMessages([]);
                    }
                } catch (error) {
                    console.error('Fetch error:', error);
                    showError('Failed to fetch messages: ' + error.message);
                    displayMessages([]);
                }
            }

            function displayMessages(messages) {
                const chatBox = document.getElementById('chat-box');
                
                if (!chatBox) {
                    console.error('Chat box element not found!');
                    return;
                }
                
                chatBox.innerHTML = '';
                
                if (!Array.isArray(messages) || messages.length === 0) {
                    chatBox.innerHTML = '<div class="message">No messages yet</div>';
                    return;
                }

                messages.forEach(message => {
                    const messageDiv = document.createElement('div');
                    messageDiv.className = 'message';
                    messageDiv.textContent = `${message.from}: ${message.text}`;
                    chatBox.appendChild(messageDiv);
                });
                
                chatBox.scrollTop = chatBox.scrollHeight;
            }

            function showError(message) {
                const errorContainer = document.getElementById('error-container');
                if (errorContainer) {
                    const errorDiv = document.createElement('div');
                    errorDiv.className = 'error-message';
                    errorDiv.textContent = message;
                    errorContainer.appendChild(errorDiv);
                    setTimeout(() => errorDiv.remove(), 5000);
                }
            }

            async function sendMessage() {
                const input = document.getElementById('message-input');
                const text = input.value.trim();
                
                if (!text) return;

                try {
                    const messageData = {
                        from: 'Home',
                        text: text
                    };
                    
                    const response = await fetch('/api/messages', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify(messageData)
                    });

                    if (!response.ok) {
                        throw new Error('Failed to send message');
                    }

                    input.value = '';
                    await fetchMessages();
                } catch (error) {
                    console.error('Send error:', error);
                    showError('Failed to send message: ' + error.message);
                }
            }

            // Start polling for messages
            fetchMessages();
            setInterval(fetchMessages, 3000);

            // Add event listener for Enter key
            document.getElementById('message-input').addEventListener('keypress', function(e) {
                if (e.key === 'Enter') {
                    sendMessage();
                }
            });
        </script>
    </body>
    </html>